server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona todas as rotas para o index.html (necessário para React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para arquivos estáticos
    location ~* \.(?:css|js|jpg|jpeg|png|gif|svg|ico|woff2?)$ {
        expires 30d;
        access_log off;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
